openapi: 3.0.1
info:
  title: Api
  description: Gateway api definition
  contact:
    name: Tarcisio Bruni
    email: tarcisiobruni@hotmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

x-amazon-apigateway-request-validators:
  params:
    validateRequestParameters: true
    validateRequestBody: false

x-amazon-apigateway-request-validator: params

paths:
  /:
    post:
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayStepFunctionsRole, Arn]
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
        httpMethod: POST
        type: aws
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: |
                { "executionId": "$input.json('executionArn').split(':').get(7) }
        requestTemplates:
          application/json:
            Fn::Sub: |-
              {
                "input": "{ \"token\": \"$input.path('$').token\" }",
                "stateMachineArn": "${NumberGenStateMachine}"
              }
      summary: Start NumberGenStateMachine instance
      responses:
        200:
          $ref: "#/components/responses/200Execution"
        403:
          $ref: "#/components/responses/Error"
components:
  schemas:
    ExecutionCreated:
      title: Created execution
      type: object
      properties:
        executionId:
          type: string
      required:
        - executionId
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  responses:
    200Execution:
      description: Result response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ExecutionCreated"
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
