AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-api-statemachine

  Sample SAM Template for aws-api-statemachine

Parameters:
  OpenAPIS3File:
    Description: '"openapi.yaml" file location'
    Default: ./openapi.yaml
    Type: String

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    MemorySize: 256

Resources:
  ApiGatewayStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Join ["", ["/", !Ref "AWS::StackName", "/"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowApiGatewayServiceToAssumeRole
            Effect: Allow
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: CallStepFunctions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "states:StartExecution"
                Resource: !Ref NumberGenStateMachine
        - PolicyName: DescribeStepFunctionExecutions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "states:DescribeExecution"
                Resource: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:${NumberGenStateMachine.Name}:*

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Name: !Sub ${AWS::StackName}-api
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: !Ref OpenAPIS3File

  StateExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "StatesExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource:
                  - !GetAtt GenNumberFunction.Arn
                  - !GetAtt EnrichFunction.Arn
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource:
                  - !GetAtt TransactionTable.Arn
              - Effect: Allow
                Action:
                  - "logs:*"
                Resource: "*"

  MyStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1

  NumberGenStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Name: NumGenStateMachineExpress
      Type: EXPRESS
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt MyStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Role: !GetAtt StateExecutionRole.Arn
      DefinitionUri: statemachine/generator.asl.json
      DefinitionSubstitutions:
        GenNumberFunctionArn: !GetAtt GenNumberFunction.Arn
        EnrichFunctionArn: !GetAtt EnrichFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable

  GenNumberFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/number-generator/
      Handler: app.lambdaHandler

  EnrichFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/enrich-object/
      Handler: app.lambdaHandler

  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # NumberGenStateMachine HourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  NumberGenStateMachineArn:
    Description: "number generator state machine ARN"
    Value: !Ref NumberGenStateMachine
